version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: Lr3
      MYSQL_USER: Van
      MYSQL_PASSWORD: 74750207
      MYSQL_HOST: db
    expose:
      - "3306"

  downloadder_bot:
    image: ashraven/downbot
    container_name: downbot
    restart: always
    depends_on:
      - db
